define(["oskari","jquery","bundles/framework/bundle/featuredata/instance","bundles/framework/bundle/featuredata/PopupHandler","bundles/framework/bundle/featuredata/plugin/MapSelectionPlugin","bundles/framework/bundle/featuredata/event/FinishedDrawingEvent","bundles/framework/bundle/featuredata/event/AddedFeatureEvent","bundles/framework/bundle/featuredata/Flyout","bundles/framework/bundle/featuredata/plugin/FeaturedataPlugin","bundles/framework/bundle/featuredata/service/GridJsonService","bundles/framework/bundle/featuredata/service/GridModelManager","bundles/framework/bundle/featuredata/domain/WfsGridUpdateParams","bundles/framework/bundle/featuredata/request/ShowFeatureDataRequest","bundles/framework/bundle/featuredata/request/ShowFeatureDataRequestHandler","css!resources/framework/bundle/featuredata/css/style.css","bundles/framework/bundle/featuredata/locale/bg","bundles/framework/bundle/featuredata/locale/cs","bundles/framework/bundle/featuredata/locale/da","bundles/framework/bundle/featuredata/locale/de","bundles/framework/bundle/featuredata/locale/en","bundles/framework/bundle/featuredata/locale/es","bundles/framework/bundle/featuredata/locale/et","bundles/framework/bundle/featuredata/locale/fi","bundles/framework/bundle/featuredata/locale/ka","bundles/framework/bundle/featuredata/locale/el","bundles/framework/bundle/featuredata/locale/hr","bundles/framework/bundle/featuredata/locale/hu","bundles/framework/bundle/featuredata/locale/lv","bundles/framework/bundle/featuredata/locale/nl","bundles/framework/bundle/featuredata/locale/pl","bundles/framework/bundle/featuredata/locale/pt","bundles/framework/bundle/featuredata/locale/ro","bundles/framework/bundle/featuredata/locale/sr","bundles/framework/bundle/featuredata/locale/sl","bundles/framework/bundle/featuredata/locale/sk","bundles/framework/bundle/featuredata/locale/sq","bundles/framework/bundle/featuredata/locale/sv","bundles/framework/bundle/featuredata/locale/uk"], function(Oskari,jQuery) {
    return Oskari.bundleCls("featuredata").category({create: function () {
        var me = this;
        var inst = Oskari.clazz.create("Oskari.mapframework.bundle.featuredata.FeatureDataBundleInstance");

        return inst;

    },update: function (manager, bundle, bi, info) {

    }})
});