SET CURRENT=%CD%
SET YUICOMPRESSOR=%CURRENT%/"../tools/bundle/yui/yuicompressor-2.4.6.jar"
pushd "bundle/openlayers-map"
md build
java -jar %YUICOMPRESSOR% --charset UTF-8 --line-break 4096 --type js bundle.js > build/bundle-yui.js
echo /* This is a packed Oskari bundle (bundle script version Fri Feb 10 2012 11:02:26 GMT+0200 (Suomen normaaliaika)) */ > build/yui.js
echo /* This is a unpacked Oskari bundle (bundle script version Fri Feb 10 2012 11:02:26 GMT+0200 (Suomen normaaliaika)) */ > build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\proj4js-1.0.1\lib\proj4js-compressed.js" >> build/yui-pack.js
type "defs.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes\Class.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Util.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes\Bounds.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes\Date.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes\Element.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes\LonLat.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes\Pixel.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\BaseTypes\Size.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Console.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Tween.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Kinetic.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\Rico\Corner.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\Rico\Color.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Ajax.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Events.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Request.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Request\XMLHttpRequest.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Projection.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Map.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Icon.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Marker.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Marker\Box.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Popup.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Tile.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Tile\Image.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Tile\Image\IFrame.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\Image.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\EventPane.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\FixedZoomLevels.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\HTTPRequest.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\Grid.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\Markers.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\Text.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\WMS.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\WMS\Untiled.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\WMS\Post.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\WMTS.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Popup\Anchored.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Popup\AnchoredBubble.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Popup\Framed.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Popup\FramedCloud.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Feature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Feature\Vector.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Feature\WFS.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Click.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Hover.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Point.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Path.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Polygon.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Feature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Drag.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Pinch.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\RegularPolygon.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Box.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\MouseWheel.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Handler\Keyboard.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Attribution.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Button.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ZoomBox.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ZoomToMaxExtent.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\DragPan.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Navigation.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\PinchZoom.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\TouchNavigation.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\MouseDefaults.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\MousePosition.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\OverviewMap.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\KeyboardDefaults.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\PanZoom.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\PanZoomBar.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ArgParser.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Permalink.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Scale.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ScaleLine.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Snapping.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Split.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\LayerSwitcher.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\DrawFeature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\DragFeature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ModifyFeature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Panel.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\SelectFeature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\NavigationHistory.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Measure.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\WMSGetFeatureInfo.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\WMTSGetFeatureInfo.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\TransformFeature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\Rectangle.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\Collection.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\Point.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\MultiPoint.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\Curve.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\LineString.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\LinearRing.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\Polygon.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\MultiLineString.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\MultiPolygon.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Geometry\Surface.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Renderer.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Renderer\Elements.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Renderer\NG.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Renderer\SVG.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Renderer\SVG2.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Renderer\Canvas.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Renderer\VML.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\Vector.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Layer\Vector\RootContainer.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Strategy.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Strategy\Filter.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Strategy\Fixed.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Strategy\Cluster.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Strategy\BBOX.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Filter.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Filter\FeatureId.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Filter\Logical.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Filter\Comparison.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Filter\Spatial.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Filter\Function.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Protocol.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Protocol\HTTP.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Style.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Style2.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\StyleMap.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Rule.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Format.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Format\XML.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Format\XML\VersionedOGC.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Format\OWSCommon.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Format\OWSCommon\v1.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Format\OWSCommon\v1_0_0.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Format\OWSCommon\v1_1_0.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\GetFeature.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\MouseToolbar.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\NavToolbar.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\PanPanel.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Pan.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ZoomIn.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ZoomOut.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\ZoomPanel.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\EditingToolbar.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Control\Geolocate.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Symbolizer.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Symbolizer\Point.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Symbolizer\Line.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Symbolizer\Polygon.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Symbolizer\Text.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Symbolizer\Raster.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Lang.js" >> build/yui-pack.js
type "..\..\..\..\map-application-framework\lib\OpenLayers-2.11\lib\OpenLayers\Lang\en.js" >> build/yui-pack.js
java -jar %YUICOMPRESSOR% --charset UTF-8 --line-break 4096 --type js build/yui-pack.js >> build/yui.js
popd
pushd "../tools/bundle/yui"
md build
java -jar %YUICOMPRESSOR% --charset UTF-8 --line-break 4096 --type js bundle.js > build/bundle-yui.js
echo /* This is a packed Oskari bundle (bundle script version Fri Feb 10 2012 11:02:26 GMT+0200 (Suomen normaaliaika)) */ > build/yui.js
echo /* This is a unpacked Oskari bundle (bundle script version Fri Feb 10 2012 11:02:26 GMT+0200 (Suomen normaaliaika)) */ > build/yui-pack.js
type "yui.js" >> build/yui-pack.js
java -jar %YUICOMPRESSOR% --charset UTF-8 --line-break 4096 --type js build/yui-pack.js >> build/yui.js
popd