(function(m,n,d){function p(a){f.current!==null&&(f.current.dragProcess(a),j.checkHover(a,f.current))}function q(a){f.current!==null&&f.current.dragStop(a)}var h=d.$,r=d.$w,s=d.Class,u=d.isHash,v=d.isArray,o=d.Element,t=d.Observer,f=new s(t,{extend:{version:"2.2.4",EVENTS:r("before start drag stop drop"),Options:{handle:null,snap:0,axis:null,range:null,dragClass:"dragging",clone:false,revert:false,revertDuration:"normal",scroll:true,scrollSensitivity:32,zIndex:1E7,moveOut:false,relName:"draggable"},
current:null,rescan:function(a){var b=this.Options.relName,c=this===f?"draggable":"droppable";(h(a)||h(n)).find('*[rel^="'+b+'"]').each(function(a){a[c]||new this(a,(new Function("return "+a.get("data-"+b)))()||{})},this)}},initialize:function(a,b){this.element=h(a);this.$super(b);this._dragStart=d(function(a){a.which===1&&this.dragStart(a)}).bind(this);this.handle.on({mousedown:this._dragStart,touchstart:this._dragStart,change:function(){me.element.css("height","auto")}});this.element.draggable=
this},destroy:function(){this.handle.stopObserving("mousedown",this._dragStart).stopObserving("touchstart",this._dragStart);delete this.element.draggable;return this},setOptions:function(a){this.$super(a);this.handle=this.options.handle?h(this.options.handle):this.element;v(this.options.snap)?(this.snapX=this.options.snap[0],this.snapY=this.options.snap[1]):this.snapX=this.snapY=this.options.snap;return this},revert:function(){var a=this.clone.position(),a={top:a.y+this.ryDiff+"px",left:a.x+this.rxDiff+
"px"};this.options.revertDuration&&this.element.morph?this.element.morph(a,{duration:this.options.revertDuration,onFinish:d(this.swapBack).bind(this)}):(this.element.setStyle(a),this.swapBack());return this},dragStart:function(a){if(this._drag)return false;else this._drag=true;this.fire("before",this,a.stop());var b=this.element.position();this.xDiff=a.pageX-b.x;this.yDiff=a.pageY-b.y;this.rxDiff=this.ryDiff=0;this.element.parents().reverse().each(function(a){if(a.getStyle("position")!=="static")a=
a.position(),this.rxDiff=-a.x,this.ryDiff=-a.y},this);var c=this.element.getStyle("width"),g=this.element.getStyle("height");c=="auto"&&(c=this.element._.offsetWidth+"px");g=="auto"&&(g=this.element._.offsetHeight+"px");if(this.options.clone||this.options.revert)this.clone=(new o(this.element._.cloneNode(true))).setStyle({visibility:this.options.clone?"visible":"hidden"}).insertTo(this.element,"before");this.element.setStyle({position:"absolute",zIndex:f.Options.zIndex++,top:b.y+this.ryDiff+"px",
left:b.x+this.rxDiff+"px",width:c,height:"auto"}).addClass(this.options.dragClass);this.options.moveOut&&this.element.insertTo(n.body);this.winScrolls=h(m).scrolls();this.winSizes=h(m).size();f.current=this.calcConstraints().fire("start",this,a);this.style=this.element._.style},dragProcess:function(a){var b=a.pageX,c=a.pageY,g=b-this.xDiff,k=c-this.yDiff;if(this.ranged){if(this.minX>g)g=this.minX;if(this.maxX<g)g=this.maxX;if(this.minY>k)k=this.minY;if(this.maxY<k)k=this.maxY}if(this.options.scroll){var e=
{x:this.winScrolls.x,y:this.winScrolls.y},i=this.options.scrollSensitivity;if(c-e.y<i)e.y=c-i;else if(e.y+this.winSizes.y-c<i)e.y=c-this.winSizes.y+i;if(b-e.x<i)e.x=b-i;else if(e.x+this.winSizes.x-b<i)e.x=b-this.winSizes.x+i;if(e.y<0)e.y=0;if(e.x<0)e.x=0;if(e.y<this.winScrolls.y||e.y>this.winScrolls.y||e.x<this.winScrolls.x||e.x>this.winScrolls.x)h(m).scrollTo(this.winScrolls=e)}this.snapX&&(g-=g%this.snapX);this.snapY&&(k-=k%this.snapY);if(!this.axisY)this.style.left=g+this.rxDiff+"px";if(!this.axisX)this.style.top=
k+this.ryDiff+"px";this.fire("drag",this,a)},dragStop:function(a){this.element.removeClass(this.options.dragClass);j.checkDrop(a,this);this.options.revert?this.revert():this._drag=false;f.current=null;this.fire("stop",this,a)},swapBack:function(){this.clone&&this.clone.replace(this.element.setStyle({width:this.clone.getStyle("width"),height:this.clone.getStyle("height"),position:this.clone.getStyle("position"),zIndex:this.clone.getStyle("zIndex")||""}));this._drag=false},calcConstraints:function(){var a=
this.options.axis;this.axisX=d(["x","horizontal"]).include(a);this.axisY=d(["y","vertical"]).include(a);this.ranged=false;if(a=this.options.range){this.ranged=true;var b=h(a);b instanceof o&&(a=b.dimensions(),a={x:[a.left,a.left+a.width],y:[a.top,a.top+a.height]});if(u(a)){b=this.element.size();if(a.x)this.minX=a.x[0],this.maxX=a.x[1]-b.x;if(a.y)this.minY=a.y[0],this.maxY=a.y[1]-b.y}}return this}}),j=new s(t,{extend:{EVENTS:r("drop hover leave"),Options:{accept:"*",containment:null,overlap:null,overlapSize:0.5,
allowClass:"droppable-allow",denyClass:"droppable-deny",relName:"droppable"},rescan:f.rescan,checkHover:function(a,b){for(var c=0,g=this.active.length;c<g;c++)this.active[c].checkHover(a,b)},checkDrop:function(a,b){for(var c=0,g=this.active.length;c<g;c++)this.active[c].checkDrop(a,b)},active:[]},initialize:function(a,b){this.element=h(a);this.$super(b);j.active.push(this.element._droppable=this)},destroy:function(){j.active=j.active.without(this);delete this.element.droppable;return this},checkHover:function(a,
b){if(this.hoveredBy(a,b)){if(!this._hovered)this._hovered=true,this.element.addClass(this.options[this.allows(b)?"allowClass":"denyClass"]),this.fire("hover",b,this,a)}else if(this._hovered)this._hovered=false,this.reset().fire("leave",b,this,a)},checkDrop:function(a,b){this.reset();this.hoveredBy(a,b)&&this.allows(b)&&(b.fire("drop",this,b,a),this.fire("drop",b,this,a))},reset:function(){this.element.removeClass(this.options.allowClass).removeClass(this.options.denyClass);return this},hoveredBy:function(a,
b){var c=this.element.dimensions(),g=c.top,k=c.left,e=c.left+c.width,i=c.top+c.height,d=a.pageX,f=a.pageY;if(this.options.overlap){var l=b.element.dimensions(),d=this.options.overlapSize,f=l.top,h=l.left,j=l.left+l.width,l=l.top+l.height;switch(this.options.overlap){case "x":case "horizontal":return(f>g&&f<i||l>g&&l<i)&&(h>k&&h<e-c.width*d||j<e&&j>k+c.width*d);case "y":case "vertical":return(h>k&&h<e||j>k&&j<e)&&(f>g&&f<i-c.height*d||l<i&&l>g+c.height*d);default:return(h>k&&h<e-c.width*d||j<e&&j>
k+c.width*d)&&(f>g&&f<i-c.height*d||l<i&&l>g+c.height*d)}}else return d>k&&d<e&&f>g&&f<i},allows:function(a){if(this.options.containment&&!this._scanned)this.options.containment=d(this.options.containment).map(h),this._scanned=true;return(this.options.containment?this.options.containment.includes(a.element):true)&&(this.options.accept=="*"?true:a.element.match(this.options.accept))}});h(n).on({ready:function(){f.rescan();j.rescan()},mousemove:p,touchmove:p,mouseup:q,touchend:q});o.include({makeDraggable:function(a){new f(this,
a);return this},undoDraggable:function(){"draggable"in this&&this.draggable.destroy();return this},makeDroppable:function(a){new j(this,a);return this},undoDroppable:function(){"droppable"in this&&this.droppable.destroy();return this}});m.Draggable=d.Draggable=f;m.Droppable=d.Droppable=j})(window,document,RightJS);
